import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function visualizeProduct(
  base64Image: string,
  mimeType: string,
  medium: string,
  imageSize: "512px" | "1K" | "2K" | "4K" = "1K",
  aspectRatio: "1:1" | "3:4" | "4:3" | "9:16" | "16:9" = "1:1"
): Promise<string> {
  const prompt = `Visualize this product in a professional marketing setting on a ${medium}. 
  The product should be the central focus and look exactly like the original image. 
  Ensure the lighting, shadows, and perspective are realistic for the ${medium} setting.`;

  const response = await ai.models.generateContent({
    model: 'gemini-3.1-flash-image-preview',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Image,
            mimeType: mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
    config: {
      imageConfig: {
        imageSize: imageSize,
        aspectRatio: aspectRatio,
      },
    },
  });

  let imageUrl = "";
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      const base64EncodeString = part.inlineData.data;
      imageUrl = `data:image/png;base64,${base64EncodeString}`;
      break;
    }
  }

  if (!imageUrl) {
    throw new Error("No image was generated by the AI.");
  }

  return imageUrl;
}

export async function refineVisualization(
  base64Image: string,
  mimeType: string,
  refinementPrompt: string,
  imageSize: "512px" | "1K" | "2K" | "4K" = "1K",
  aspectRatio: "1:1" | "3:4" | "4:3" | "9:16" | "16:9" = "1:1"
): Promise<string> {
  const prompt = `Refine this product visualization based on the following request: "${refinementPrompt}". 
  Maintain the core product's appearance and the overall setting, but apply the requested adjustments accurately.`;

  const response = await ai.models.generateContent({
    model: 'gemini-3.1-flash-image-preview',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Image,
            mimeType: mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
    config: {
      imageConfig: {
        imageSize: imageSize,
        aspectRatio: aspectRatio,
      },
    },
  });

  let imageUrl = "";
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      const base64EncodeString = part.inlineData.data;
      imageUrl = `data:image/png;base64,${base64EncodeString}`;
      break;
    }
  }

  if (!imageUrl) {
    throw new Error("No image was generated by the AI.");
  }

  return imageUrl;
}
